### ISSUE TITLE
Is the "none" config option working?

### ISSUE THREAD

**Issue by Josral** [Coders-After-Dark/Reskillable#139]
I have tried:

tp=reskillable:mining|3
tp:cooked_apple:*="none"

and I"m left with a cooked apple requiring mining 3.  What am I doing wrong? Thanks.

**Comment by pupnewfster** [comment]
Try `tp:cooked_apple:*=none`

**Comment by Josral** [comment]
same result.  Oh I see in the closed issues someone had a problem with the 'none' config option not working back in May.

**Comment by pupnewfster** [comment]
That was fixed in version 1.7.0. When the transition from Skillable to Reskillable was made the functionality had been lost in the rewrite of how locking works. I know that currently it is working given I use it a fair bit in my own pack. I will look into a bit later today given maybe it just is not reading it from the config properly. (Given I set all the requirements in my pack using CompatSkills, so maybe it is just an issue with reading from the config)

**Comment by Josral** [comment]
I have over a hundred mods in my current set-up but have a testing instance to throw everything out to rule out interactions with other mods.  With just forge, tiny progressions, jei, and reskillable, I get the same behavior.  'none' config option not working with or without quotes.

**Comment by pupnewfster** [comment]
Odd, I don't have time to test it right now but sometimes in the past items do not get noticed properly with the wildcard `:*` if they do not have durability/multiple types.
`tp:cooked_apple=none` may work if not when I get a chance I will load up a world with it and test

**Comment by Josral** [comment]
removing the wildcard was unsuccessful.

**Comment by Josral** [comment]
I tried -
tp:cooked_apple=reskillable:mining|1
tp:cooked_apple=reskillable:mining|2
tp:cooked_apple=reskillable:mining|4

to see what would happen.  In the case of mining 1 & 2 nothing.  Mining of 3 held so could not lower the requirement.  Although mining 4 did work.  Can increase requirement but not lower it.  Still no luck with 'none'.

**Comment by pupnewfster** [comment]
I did a little testing and it seems that the config file is not properly supporting `none` as an option (or at least is not in this case). I don't quite have time to look into fixing it right now and even once I do not sure when an update would be released.

I also tried it through CompatSkills using the below in a CraftTweaker script and it worked properly:
```
mods.compatskills.ModLock.addModLock("tp", "reskillable:mining|3");
mods.compatskills.Requirement.addRequirement(<tp:cooked_apple>, "none");
```

So my suggestion for now is to just use CompatSkills until I get a chance to look into and fix the issue. (On the bright side CompatSkills also lets you lock a lot of other things and have more different Requirements.)
